apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
spec:
  {{- if .Values.config.autoscaling.enabled }}
  replicas: {{ .Values.app.spec.replicas }}
  {{- end }}
  selector:
    matchLabels:
      component: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        component: {{ .Values.app.name }}
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: gcr.io/cloud-solutions-images/{{ .Values.app.name }}
