apiVersion: v1
kind: Pod
metadata:
  name: "demo-shell"
  namespace: default
  labels:
    app: "demo-shell"
spec:
  containers:
  - name: demo-shell
    image: "nginx"
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 150m
        memory: 200Mi
    ports:
    - containerPort:  8080
      name:  http
  restartPolicy: Always