apiVersion: apps/v1
kind: Deployment
metadata:
  name:  webserver
  namespace: default
  labels:
    app:  webserver
spec:
  selector:
    matchLabels:
      app: webserver
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  webserver
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  webserver
        image:  nginx
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /_status/healthz
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        env:
        - name: MY_NAME
          valueFrom:
            configMapKeyRef:
              name: webserver
              key: MY_NAME
        ports:
        - containerPort:  80
          name:  webserver
        volumeMounts:
        - name: localtime
          mountPath: /tmp/test-volume
      volumes:
        - name: localtime
          hostPath:
            path: /tmp/test-volume
      restartPolicy: Always
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: MY_NAME
  namespace: default
data:
  key: MY_NAME
  value: "hi"