apiVersion: v2
appVersion: 1.16.0
dependencies:
- condition: fluentbit.enabled
  name: fluentbit
  repository: file://charts/fluentbit
- condition: tester.enabled
  name: tester
  repository: file://charts/tester
description: A Helm chart for Kubernetes
name: logging
type: application
version: 0.2.0
